services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=LeadDB;Trusted_Connection=True;TrustServerCertificate=True;
